config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'kanji#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "kanji_cards", to: "kanji_cards#index"

  get "kanji_cards/:id", to: "kanji_cards#show"

  get "kanji_cards/:id/edit", to: "kanji_cards#edit"
  patch "kanji_cards/:id", to: "kanji_cards#update"

  delete "kanji_cards/:id", to: "kanji_cards#destroy"

  resources :kanji, only: [:index, :show]
  resources :searches

end
	

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kanji.rb
class Kanji < ApplicationRecord
  has_many :kanji_cards
  validates :character, uniqueness: true
end

app/models/kanji_card.rb
class KanjiCard < ApplicationRecord
  belongs_to :user
  belongs_to :kanji
  validates :kanji_id, uniqueness: true


  MAX_GRADE = 5
    # 0 = really hard to answer / 5 = really easy to answer
    # D_EF[q] = (0.1 - (MAX_GRADE - grade) * (0.08 + (MAX_GRADE - grade) * 0.02))
    D_EF = {
      5 => 0.1,
      4 =>  0,
      3 => -0.14,
      2 => -0.32,
      1 => -0.54,
      0 => -0.8
    }.freeze

  def next_interval(grade)
    grade = MAX_GRADE if grade > MAX_GRADE

    if grade >= 3
      if self.repetition == 0
        self.interval = 1
        self.repetition = 1
      elsif repetition == 1
        self.interval = 6
        self.repetition = 2
      else
        self.interval = (interval * easiness_factor).round
        self.repetition = repetition + 1
      end
    else
      self.repetition = 0
      self.interval = 1
    end

    self.easiness_factor = (easiness_factor + D_EF[grade]).round(2)
    self.easiness_factor = easiness_factor < 1.3 ? 1.3 : easiness_factor

    return interval
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :kanji_cards, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/kanji_cards_controller.rb
class KanjiCardsController < ApplicationController

  def index

  end

  # def show
  #   @card = KanjiCard.find(params[:id])
  # end

  # def edit
  #   @card = KanjiCard.find(params[:id])
  # end

  # def update
  #   @card = KanjiCard.find(params[:id])
  #   @card.save
  # end

  # def destroy
  #   @card = KanjiCard.find(params[:id])
  #   @card.destroy
  # end
end

app/controllers/kanji_controller.rb
class KanjiController < ApplicationController

  def index
    if params[:query].present?
      sql_query = " \
        character ILIKE :query \
        OR koohii1 ILIKE :query \
        OR koohii2 ILIKE :query \
        OR onyomi ILIKE :query \
        OR kunyomi ILIKE :query \
        OR english ILIKE :query \
        OR keyword ILIKE :query \
        "
      @kanji = Kanji.where(sql_query, query: "%#{params[:query]}%")
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      @kanji = Kanji.all
    end
  end

  def show
    @kanji = Kanji.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kanji/index.html.erb
<div class="kanji-explorer">
  <h1> 
    Kanji Explorer 
  </h1>
  <p>
    Here are some things you can type into the search box to look for Kanji and examples.
  </p>
  <ul>
    <li>
      <em>Kanji</em> - Input kanji directly to find characters containing these kanji, or associated radicals
    </li>
    <li>
      <em>Stories</em> - Stories from Koohii
    </li>
    <li>
      <em>Heisig Keyword</em> - Keywords for Heisig's book "Remembering the Kanji"
    </li>
    <li>
      <em>Kunyomi or Onyomi readings</em> - Input the reading in Japanese hiragana or katakana for onyomi/kunyomi respectively
    </li>
  </ul>
  <%= render 'shared/search_form' %>
</div>
<%= link_to "Advanced Search", new_search_path %>

<div class="kanji-results">
  <div class="row">
  <% @kanji.each do |kanji| %>
    <div class="col-md-3">
      <%= link_to kanji_path(kanji), class: 'kanji_box' do %>
        <div class="kanji_index">
          <%= kanji.character %>
        </div> 
      <% end %>    
    </div>
  <% end %>
  </div>
</div>

app/views/kanji/show.html.erb
<h1><%= @kanji.character %><h1>
<h5>Heisig Keyword</h5><%= @kanji.keyword %>
<p></p>
<h5>Kunyomi:</h5>
<p><%= @kanji.kunyomi %></p>
<h5>Onyomi:</h5>
<p><%= @kanji.onyomi %></p>
<h5>Koohii Story 1:</h5>
<p><%= @kanji.koohii1%></p>
<h5>Koohii Story 2:</h5>
<p><%= @kanji.koohii2%></p>
<h5>English:</h5>
<p><%= @kanji.english %></p>
<h5>Examples:</h5>
<p><%= @kanji.examples.html_safe %></p>

app/views/kanji_cards/index.html.erb
<h1> Kanji Explorer </h1>
<% if params[:query].present? %>
  <h2> Search term: <%= params[:query] %> </h2>
<% end %>
<%= form_tag kanji_cards_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Enter JLPT Level"
  %>
<% end %>
<% @kanji.each do |kanji| %>
  <%= link_to kanji.character, kanji_path(kanji), class: 'kanji_index' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>iikanji kanji explorer</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="wrapper">
      <div class="container">
        <%= yield %>
        <%= javascript_include_tag 'application' %>
        <%= javascript_pack_tag 'application' %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>iikanji home</h1>
<p>go to the <%= link_to "Kanji cards Index", kanji_cards_path %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light" style="background-color: white;">
  <%= link_to image_tag('iikanji.png', alt:'brand', height: '40px'), root_path, class: 'navbar-brand' %>
</nav>

app/views/shared/_search_form.html.erb
<%= simple_form_for :search, url: kanji_index_path, remote: true, method: :get do |f| %>
  <fieldset class="form-group">
  	<legend class="col-form-label pt-0">JLPT level</legend>
  	<div class="custom-control custom-checkbox custom-control-inline">
      <input class="custom-control-input" type="checkbox" id="exampleInlineCheckbox1" name="query[jlpt]" value="1" required="">
      <label class="custom-control-label" for="exampleInlineCheckbox1">N1</label>
    </div>
    <div class="custom-control custom-checkbox custom-control-inline">
      <input class="custom-control-input" type="checkbox" id="exampleInlineCheckbox2" name="query[jlpt]" value="2" required="">
      <label class="custom-control-label" for="exampleInlineCheckbox2">N2</label>
    </div>
    <div class="custom-control custom-checkbox custom-control-inline">
      <input class="custom-control-input" type="checkbox" id="exampleInlineCheckbox3" name="query[jlpt]" value="3" required="">
      <label class="custom-control-label" for="exampleInlineCheckbox3">N3</label>
    </div>
    <div class="custom-control custom-checkbox custom-control-inline">
      <input class="custom-control-input" type="checkbox" id="exampleInlineCheckbox4" name="query[jlpt]" value="4" required="">
      <label class="custom-control-label" for="exampleInlineCheckbox4">N4</label>
    </div>
    <div class="custom-control custom-checkbox custom-control-inline">
      <input class="custom-control-input" type="checkbox" id="exampleInlineCheckbox5" name="query[jlpt]" value="5" required="">
      <label class="custom-control-label" for="exampleInlineCheckbox5">N5</label>
    </div>
  </fieldset>
	
	<div class="search-form-control form-group">
	  <input class="form-control string required" type="text" name="query" id="search_query" placeholder="Enter your search terms here" />
	</div>

	
	<button name="button" type="submit" class="btn btn-flat">
	  <i class="fas fa-search"></i> Search
	</button>
	  
<% end %>

<!-- <div class="form-check-inline">
  <label class="form-check-label">
    <input class="form-check-input" type="checkbox" name="jlpt" value="5">
    JLPT 5
  </label>
</div> -->